### ISSUE TITLE
Title 

### ISSUE THREAD

**Issue by Jooyoung114** [TrinityEdu/DigiNinja#1]
asdf asdf

**Comment by vishal-reddy** [comment]
got the notifcation, here is some interaction

**Comment by vishal-reddy** [comment]
I just answered your question @TrinEdu

**Comment by vishal-reddy** [comment]
@TrinEdu, are you satisfied with the answer?

**Comment by Jooyoung114** [comment]
Yep, thanks.

**Comment by vishal-reddy** [comment]
Closing!
