### ISSUE TITLE
How do I do this?

### ISSUE THREAD

**Issue by trinity-edu-student-demo** [TrinityEdu/DigiNinja#2]
I have something setup.

I have code like this:

`console.log("Hello Vishal Reddy")`

I am having a problem with something.

**Comment by vishal-reddy** [comment]
@trinity-edu-student-demo can you give me more details please?

**Comment by trinity-edu-student-demo** [comment]
@vishal-reddy here are some more details

**Comment by vishal-reddy** [comment]
@trinity-edu-student-demo thank you. I have the solution to your problem. Here it is....

**Comment by trinity-edu-student-demo** [comment]
@Thomas-Stewart ccing Thomas. Sorry Dude you are part of a demo.
