### ISSUE TITLE
What are the main functions of metadatas on the browsers.

### ISSUE THREAD

**Issue by Peter-Omanga** [TrinityEdu/DigiNinja#6]
![metadata](https://user-images.githubusercontent.com/11257091/30932110-2bc465d0-a3cf-11e7-8047-a53770055c53.PNG)

<meta charset="utf-8"/>: Tells the web browser which character set to use. In this case, the character set is "utf-8"

1.what are these characters ? 
2.How does all this work on a browser ?

**Comment by vishal-reddy** [comment]
Hi Peter,

Please take a look at this link: https://www.w3schools.com/html/html_charset.asp
Please let me know if that answered your question.

**Comment by Peter-Omanga** [comment]
Thanks it now makes perfect sense.

**Comment by vishal-reddy** [comment]
sounds good!
